version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vehicleworkshop-postgres
    environment:
      POSTGRES_DB: vehicleworkshop
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-ChichiricumandingA123321..}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vehicleworkshop-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: vehicleworkshop-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicleworkshop
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-ChichiricumandingA123321..}
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - vehicleworkshop-network
    restart: unless-stopped

networks:
  vehicleworkshop-network:
    driver: bridge

volumes:
  postgres_data:
